### ISSUE TITLE
InApp: Nudge Template: Impressions are not tracked

### ISSUE THREAD

**Issue by shahp00ja** [moengage/MoEngage-iOS-SDK#1]
Expected: API for Impressions should be called to update stats on Info page

<img width="1085" alt="screen shot 2015-08-06 at 2 27 34 pm" src="https://cloud.githubusercontent.com/assets/12966925/9108645/4386634e-3c4d-11e5-9fa7-d0bd51ae0715.png">

+ @yashwanth2

**Comment by gautamMoEngage** [comment]
It's been fixed and tested by you. You can close it @shahp00ja
