### ISSUE TITLE
Leaks by Instruments

### ISSUE THREAD

**Issue by ihsanhusnul** [moengage/MoEngage-iOS-SDK#13]
Hi, we would like to report that your SDK was detected leaked by Instrument.
a very large percentage for the scale of leakage.
below is call tree of a leak
<img width="523" alt="Screen Shot 2020-03-13 at 09 46 04" src="https://user-images.githubusercontent.com/3015018/76585096-12f2b700-6510-11ea-86eb-bf34cee8a4af.png">

Environment :
- XCode 11.3.1
- Profiling on device iPhone X
- iOS 13.3.1
- SDK version 4.3.2

hope the next release was solving this issue, thanks.

**Comment by ChengappaMoEngage** [comment]
Hi @ihsanhusnul, We have fixed a lot of these leaks in the recent releases. The current SDK version is 6.0.0. Please update to the latest SDK version, and you should not be seeing these leaks with this version.
