### ISSUE TITLE
MoEngage - Live Push Notification Issue - Failed To Send BadDeviceToken

### ISSUE THREAD

**Issue by twcjogendra** [moengage/MoEngage-iOS-SDK#15]
In my project  Push notification working fine in Test Mode. 
When I switch on Live mode and send push notification on iOS Device showing this error. 
I have created build with production and checked every thing.
Please suggest what I'm missing in this.

**Comment by ChengappaMoEngage** [comment]
Live mode/environment will only work for AppStore or Adhoc distribution build. Follow the links below to get more info:
[Bad Device Token](https://docs.moengage.com/docs/troubleshooting#section-getting-bad-device-token-error-while-sending-the-push-notifications)
[Test/Live Environment](https://docs.moengage.com/docs/appdelegate-changes#section-testlive-environment)

**Comment by twcjogendra** [comment]
My Tracking data is showing in Moengage Dashboard and I also installed app from AdHoc  Env. 
My Device log is showing in recent activity , only push notification is not working.
Is there any option to test or I'm making any silly mistake

**Comment by ChengappaMoEngage** [comment]
@twcjogendra Would advise you to reach out to our support team, they would help you with your queries.

**Comment by StarryFire** [comment]
How am i supposed to test my release build? Isnt it counter intuitive to expect the developer to release to app store directly?

**Comment by ChengappaMoEngage** [comment]
@StarryFire As mentioned above in Dashboard we have Test and Live modes, wherein Test mode is meant for development builds and Live for Adhoc and AppStore builds. You can test your Release build in Testflight, OR alternatively you can temporarily update the build configuration in Archive to debug(In Edit scheme) to do the testing in development build. You can refer to the docs shared above and if you still have queries regarding this please reach out to our support team, they will help you out with the integration.
