### ISSUE TITLE
MoEngage - App Crash on Launch v6.0.2

### ISSUE THREAD

**Issue by arpitarora-wynk** [moengage/MoEngage-iOS-SDK#16]
<img width="802" alt="Screenshot 2020-05-27 at 11 59 47 AM" src="https://user-images.githubusercontent.com/41051653/82985403-9b61fd80-a011-11ea-9137-70a36b19909e.png">
Hi Team,

We have observed that we are getting crash for some user on app launch or app upgrade. 
We have recently moved to v6.0.2 from v4.3.0. 

EXC_BAD_ACCESS KERN_INVALID_ADDRESS

Stacktrace - 
libobjc.A.dylib
objc_retain + 16

MoEngageCore
-[NSMutableDictionary(MOExtension) setObjectNilHandled:forKey:] + 56

MoEngageCore
+[MONetworkUtils getRequestParamsForV2] + 720

MoEngageCore
+[MONetworkUtils getRequestParamsWithV1:] + 68

MoEngageCore
+[MONetworkUtils getQueryParamsBodyDictForService:] + 92

MOMessaging
-[MODeviceTriggersHandler getDeviceTriggerSyncRequestPayload] + 276

MOMessaging
-[MODeviceTriggersHandler syncDeviceTriggersWithCompletionBlock:] + 80

MOMessaging
-[MOMessaging syncRealTimeTriggersWithCompletionBlock:] + 280

MOMessaging
-[MOMessaging updateModules] + 168

MOMessaging
-[MOMessaging initializeMessagingWithLaunchOptions:] + 100

MoEngage
-[MoEngage initializeWithAppID:withLaunchOptions:] + 276

MoEngage
-[MoEngage initializeProdWithAppID:withLaunchOptions:] + 292

Calling this initialize method from a wrapper written for MoEngage specially which is being called from DidFinishLaunchingWithOptions:

**Comment by TheSPST** [comment]
> <img alt="Screenshot 2020-05-27 at 11 59 47 AM" width="802" src="https://user-images.githubusercontent.com/41051653/82985403-9b61fd80-a011-11ea-9137-70a36b19909e.png">
> 
> Hi Team,
> We have observed that we are getting crash for some user on app launch or app upgrade.
> We have recently moved to v6.0.2 from v4.3.0.
> 
> EXC_BAD_ACCESS KERN_INVALID_ADDRESS
> 
> Stacktrace -
> libobjc.A.dylib
> objc_retain + 16
> 
> MoEngageCore
> -[NSMutableDictionary(MOExtension) setObjectNilHandled:forKey:] + 56
> 
> MoEngageCore
> +[MONetworkUtils getRequestParamsForV2] + 720
> 
> MoEngageCore
> +[MONetworkUtils getRequestParamsWithV1:] + 68
> 
> MoEngageCore
> +[MONetworkUtils getQueryParamsBodyDictForService:] + 92
> 
> MOMessaging
> -[MODeviceTriggersHandler getDeviceTriggerSyncRequestPayload] + 276
> 
> MOMessaging
> -[MODeviceTriggersHandler syncDeviceTriggersWithCompletionBlock:] + 80
> 
> MOMessaging
> -[MOMessaging syncRealTimeTriggersWithCompletionBlock:] + 280
> 
> MOMessaging
> -[MOMessaging updateModules] + 168
> 
> MOMessaging
> -[MOMessaging initializeMessagingWithLaunchOptions:] + 100
> 
> MoEngage
> -[MoEngage initializeWithAppID:withLaunchOptions:] + 276
> 
> MoEngage
> -[MoEngage initializeProdWithAppID:withLaunchOptions:] + 292
> 
> Calling this initialize method from a wrapper written for MoEngage specially which is being called from DidFinishLaunchingWithOptions:

Facing same issue did you find any solution ? ?? ?

**Comment by ChengappaMoEngage** [comment]
@TheSPST We had released a fix for this in the version 6.1.1, please update to the latest version of SDK and update here if still facing issues.
