### ISSUE TITLE
App Crash While App Is On Foreground

### ISSUE THREAD

**Issue by zaimramlan** [moengage/MoEngage-iOS-SDK#17]
Hi Team,
We noticed that some of our users have recently experience crashes while exploring the app. Any help would be appreciated.

### MoEngage
Framework: v4.4.0
Installation: via `Podfile` - `pod 'MoEngage-iOS-SDK','4.4.0'`

### Sample Devices
Model: iPhone 6s/7/8 Plus
iOS: 13.5.x and above

## Stacktrace
<img width="1100" alt="Screenshot 2020-08-03 at 6 15 52 PM" src="https://user-images.githubusercontent.com/6073623/89172538-62b44680-d5b5-11ea-952e-7cedfc4f2058.png">
<img width="1098" alt="Screenshot 2020-08-03 at 6 07 05 PM" src="https://user-images.githubusercontent.com/6073623/89172545-65af3700-d5b5-11ea-8afa-6654ee18bd15.png">

*It is shown as hidden as we don't have the symbols for the MoEngage framework.
** Wouldn't mind to reattach screenshot if we could obtain the dSYMs for it.

**Comment by ChengappaMoEngage** [comment]
@zaimramlan You are using a relatively older version of our SDK, could you please update to the latest SDK version and let us know if you are able to replicate the issue.
[Release Notes ](https://docs.moengage.com/docs/release-notes)

**Comment by zaimramlan** [comment]
@ChengappaMoEngage Thank you for the reply! 

To update the SDK, we'll have to have an internal review with our team first as there are some breaking changes as seen from the release notes. 

Just to be prepared before taking this to the team,
1. Would the dSYMs be provided for the latest framework version? 
(it would be helpful as we could help narrow down the issue from the crash logs - if any)

1. Seeing that Apple provided a better way to distribute binary frameworks and symbols together, would there be a support for `XCFrameworks` in the pipeline?

**Comment by ChengappaMoEngage** [comment]
@zaimramlan The dSyms for the latest SDKs you will find in the repo itself. (Inside `Frameworks` folder).
Yes, we are exploring and working on distributing the SDK as `XCFrameworks`, most probably we will do it along with the next major version update of the SDK(`7.0.0`) planned post the release of iOS 14.
