### ISSUE TITLE
Fetch Notification List

### ISSUE THREAD

**Issue by bony06aug** [moengage/MoEngage-iOS-SDK#18]
Hi Dev Team,
I am trying to fetch the list of all the messages sent via push but getting empty message array.
Can anyone help?

**Comment by saraabdulw** [comment]
Hey bony06aug,
Please raise a support ticket by sending out your issue details to this email address : support@moengage.com. Post this, the respective solutions engineer will get in touch with you.

**Comment by bony06aug** [comment]
I had integrated MoInbox,
now while using 
getInboxMessagesWithCompletionBlock method is not getting any message count, i only get messages when i click the notification banner when push arrives. Only those messages are getting fetched when I use the above described delegate message.

Moreover I want to fetch all the notifications received on the device.

Am Using iOS Sdk

**Comment by bony06aug** [comment]
Any Update on this?

**Comment by saraabdulw** [comment]
Hey bony06aug,
Closing this issue as we have addressed this via our support channel. Please get back to us if you have further queries around this by sending out your issue details to this email address : support@moengage.com.
