### ISSUE TITLE
Initialize the SDK for versions 6.X

### ISSUE THREAD

**Issue by rodrigocoliveira** [moengage/MoEngage-iOS-SDK#19]
Hello,

I am currently working in a project that integrates Segment and Moengage, so I cannot use the latest realease version 7.X of the MoEngage SDK. So I went to version 6. The problem is that on the docs is written that we need to initialize the SDK as :

`MOSDKConfig* sdkConfig = [[MOSDKConfig alloc] initWithAppID:MoEngageAppID];`

And this is throwing me the error: Use of undeclared identifier 'MOSDKConfig'. What is really obcious as MOSDKConfig was added on the 7th version. 

So to be direct... what is the method I need to call to initialize the SDK on the version 6. (I recommend adding this to the docs as well.

Thank you very much

**Comment by ChengappaMoEngage** [comment]
@rodrigocoliveira Sorry we missed replying to this issue. Not sure if you are still looking for help with this. 
But we released `Segment-MoEngage 6.0.0` with support for `MoEngage-iOS-SDK 7.0.0`. [Release Notes](https://docs.moengage.com/docs/segment-ios-releases#v600)

Regarding the older initialization methods to be used in SDK versions below `7.0.0`, you can find the information [here](https://docs.moengage.com/docs/ios-sdk-migration-700#initialisation-method-changes).

And please write to `support@moengage.com` for any help in integration for faster response.
