### ISSUE TITLE
Duplicate symbol issue : After install from pod I am getting below issues

### ISSUE THREAD

**Issue by ashishcs10** [moengage/MoEngage-iOS-SDK#2]
duplicate symbol _llvm.cmdline in:
    /TA_Project/HeadlinesToday/Svn_Code/ios/HeadLinesToday/Pods/MoEngage-iOS-SDK/libMoEngageSDK.a(MONudgeView.o)
    /TA_Project/HeadlinesToday/Svn_Code/ios/HeadLinesToday/Pods/MoEngage-iOS-SDK/libMoEngageSDK.a(MOEngageDateUtils.o)
duplicate symbol _llvm.embedded.module in:
    /TA_Project/HeadlinesToday/Svn_Code/ios/HeadLinesToday/Pods/MoEngage-iOS-SDK/libMoEngageSDK.a(MONudgeView.o)
    /TA_Project/HeadlinesToday/Svn_Code/ios/HeadLinesToday/Pods/MoEngage-iOS-SDK/libMoEngageSDK.a(MOEngageDateUtils.o)
duplicate symbol _llvm.cmdline in:
    /TA_Project/HeadlinesToday/Svn_Code/ios/HeadLinesToday/Pods/MoEngage-iOS-SDK/libMoEngageSDK.a(MONudgeView.o)
    /TA_Project/HeadlinesToday/Svn_Code/ios/HeadLinesToday/Pods/MoEngage-iOS-SDK/libMoEngageSDK.a(MoEngage.o)
duplicate symbol _llvm.embedded.module in:
    /TA_Project/HeadlinesToday/Svn_Code/ios/HeadLinesToday/Pods/MoEngage-iOS-SDK/libMoEngageSDK.a(MONudgeView.o)
    /TA_Project/HeadlinesToday/Svn_Code/ios/HeadLinesToday/Pods/MoEngage-iOS-SDK/libMoEngageSDK.a(MoEngage.o)
duplicate symbol _llvm.cmdline in:
    /TA_Project/HeadlinesToday/Svn_Code/ios/HeadLinesToday/Pods/MoEngage-iOS-SDK/libMoEngageSDK.a(MONudgeView.o)
    /TA_Project/HeadlinesToday/Svn_Code/ios/HeadLinesToday/Pods/MoEngage-iOS-SDK/libMoEngageSDK.a(MONudgesHandler.o)
duplicate symbol _llvm.embedded.module in:
    /TA_Project/HeadlinesToday/Svn_Code/ios/HeadLinesToday/Pods/MoEngage-iOS-SDK/libMoEngageSDK.a(MONudgeView.o)
    /TA_Project/HeadlinesToday/Svn_Code/ios/HeadLinesToday/Pods/MoEngage-iOS-SDK/libMoEngageSDK.a(MONudgesHandler.o)

**Comment by gautamMoEngage** [comment]
@ashishcs10 - Are you integrating via Segment? It looks like you have multiple copies of MoEngage Pods.

**Comment by ashishcs10** [comment]
Hi Team,
I am using it via cocoapods and followed your instructions, I also did it via manual installation and got the same error. Can you please try it at your end, and let me know if its working.

**Comment by gautamMoEngage** [comment]
Ok. I have some people facing the issue on the latest version, though it's different from your issue.
Try 2 things:
1. Ensure that you don't have multiple copies, one via manual installation and another via Cocoapods. That will definitely cause an issue.
2. If you are sure with point 1 and it still doesn't work, explicitly point the pod to version 1.7. That should work. 

Still if it doesn't, let me know. I'll publish another release.

**Comment by ashishcs10** [comment]
- I am using cocoapods so there is no way to add multiple copies, and I have also tries pod 1.7 still got the same issues, you can also try at your end, just create a sample project and install it via cocoapods.

**Comment by gautamMoEngage** [comment]
Solved over email conversation. The issue was that the developer had added the SDK manually as well as via Cocoapods.
