### ISSUE TITLE
In App Notification issue

### ISSUE THREAD

**Issue by avinashamanjha251** [moengage/MoEngage-iOS-SDK#21]
Hi dev team, 
I'm not getting in app campaign notification when I'm connected with Xcode with live credentials. but when I create a ad hoc build .. then I'm getting notification ... and on test server In-App NATIV is v2.

**Comment by ChengappaMoEngage** [comment]
When you directly run the app from Xcode, it's a development build(with debug Build configuration) which points to the Test environment of your account. I believe you have currently created the campaign only in the Live environment and thus see it when you export a build(with Release Configuration). 

Doc for reference explaining how SDK initialization works and when TEST or LIVE environment is considered: [link](https://docs.moengage.com/docs/appdelegate-changes#testlive-environment)

Closing it as an email thread is created with the Support team to help with the same.
