### ISSUE TITLE
DemoApp: pp:: "PUSH_PREFERENCE" is not visible on user's profile and where its visible: its false

### ISSUE THREAD

**Issue by shahp00ja** [moengage/MoEngage-iOS-SDK#3]
1. **user:** http://pp.moengage.com/v3/#/user/info/565572a38fbafe4bb28fdd93
2. its false everywhere else where the user attribute is found
**Ex.**http://pp.moengage.com/v3/#/user/info/55ba04a9f48a9f053d5d2102

<img width="1215" alt="screen shot 2015-11-25 at 2 41 57 pm" src="https://cloud.githubusercontent.com/assets/12966925/11392859/6c957216-9382-11e5-9de0-89af57b5c2ae.png">

**Comment by gautamMoEngage** [comment]
Must've been a discrepancy. It's working well since a long time. Reopen if you find it again.
