### ISSUE TITLE
ERROR ITMS 90535

### ISSUE THREAD

**Issue by virengujariya** [moengage/MoEngage-iOS-SDK#4]
Error when publishing to iOS store: ```ERROR ITMS 90535: Unexpected CFBundleExecutableKey. The bundle at 'Payload/*****.app/MoEngage.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."```

**Comment by gautamMoEngage** [comment]
Hi @virengujariya . Don't know if it's too late to comment, but this was an Apple bug, where the key "Executable file" in the plist created an issue. The latest SDK solves it. You can also solve it by removing the key from the plist in MoEngage.bundle.
