### ISSUE TITLE
MOEventHandler syncTrackedEventIn Background cause iOS App crash

### ISSUE THREAD

**Issue by EasyTaxi-iOS** [moengage/MoEngage-iOS-SDK#7]
<img width="1238" alt="screen shot 2017-12-15 at 3 58 12 pm" src="https://user-images.githubusercontent.com/27677590/34039867-19811d7e-e1b3-11e7-8f8c-50cfb847a0d9.png">
Hi,

I am getting excess bad code exception in first time APP launch for the MoEngage.

`[[MoEngage sharedInstance] initializeDevWithApiKey:@"XXXXXXXXXXXXXXXXXXX" inApplication:application withLaunch
<img width="1238" alt="screen shot 2017-12-15 at 3 58 12 pm" src="https://user-images.githubusercontent.com/27677590/34039835-fe379fc0-e1b2-11e7-95f8-58b9eff22847.png">
Options:options openDeeplinkUrlAutomatically:YES];`

I have attached screenshot for MoEngage thread which cause access bad code.

When I comment initialize of MoEngage line, my iOS APP run smoothly. Please advice, thanks

**Comment by apoorva-moengage** [comment]
Hi Team,

Let me know the below things:
1) Can you share the detailed logs which you can find on the console? That would help us debug faster.
2) Please share the screenshot where you are initialising
3) Let us know if this is happening every time or is the behaviour intermittent?

**Comment by EasyTaxi-iOS** [comment]
hi,

Thanks for writing,

1. Here is console log:

warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.

2. I am initialing MoEngage SDK in APP Delegate class method didFinishLaunchingWithOptions

    [[MoEngage sharedInstance] stop:application];
    [[MoEngage sharedInstance] applicationWillEnterForeground:application];
    [[MoEngage sharedInstance] applicationBecameActiveinApplication:application];

Above methods are deprecated, please let us know alternate to above methods for MoEnage. 

3. Access bad code error exception appear in first time APP launch for the MoEngage, when I open application second time no more exception, and App work smoothly.

**Comment by ChengappaMoEngage** [comment]
@EasyTaxi-iOS 

1. Could you provide the symbolicated crash logs for this crash? This is so that we can pinpoint exactly where its crashing in syncTrackedEventsInBackground: method.

2. These callbacks are internally handled by SDK. These application life-cycle methods are deprecated from SDK version 3.3.0. Include them only if you are using SDK version 3.2.2 or below. I believe you are using SDK version > 3.2.2, just delete the deprecated methods in this case, you don't have to call any alternative methods.

**Comment by EasyTaxi-iOS** [comment]
@ChengappaMoEngage,

Thanks for writing.

There is no console log for crashing other than I shared with you above. 

Access bad code error exception appear in MOEventHandler class and Method is syncTrackedEventInBackground. Please review attached screenshot
https://user-images.githubusercontent.com/27677590/34039835-fe379fc0-e1b2-11e7-95f8-58b9eff22847.png 

One thing more, there is no event which need to be tracked at application launch time, before user login to Easy Taxi APP.

**Comment by ChengappaMoEngage** [comment]
Can you tell me where exactly you are initializing the SDK? Are you calling trackEvent: method or any other method of the SDK before initializing the SDK.
There has to be a crash log associated with this crash. You will find the crash logs in **Window>Devices and Simulators>View Device Logs**. It will be great if you could share it.

**Comment by EasyTaxi-iOS** [comment]
Hi,

Can you tell me where exactly you are initializing the SDK?
I am initialing MoEngage SDK in APP Delegate class method didFinishLaunchingWithOptions.

Are you calling trackEvent: method or any other method of the SDK before initializing the SDK?
No

Window>Devices and Simulators>View Device Logs, Exported one crash log into file, please see thread 4 in attached crash log file.

Please do let me know if you need any additional information.

Thanks.
[Crash log.TXT](https://github.com/moengage/MoEngage-iOS-SDK/files/1567886/Crash.log.TXT)

**Comment by ChengappaMoEngage** [comment]
Thanks for the crash logs. Now could you also provide the SDK version you are using? Is it 3.8.0?

If I got it right regarding the scenario of the crash, this is happening only on the first launch of the app after integrating the SDK, post that you are not able to reproduce it.

**Comment by EasyTaxi-iOS** [comment]
Hi,

I integrated MoEngage SDK with the help of Pod, Yes its 3.8.0

the scenario of the crash, this is happening only on the first launch of the app after integrating the SDK. Your are right.

I can reproduce ofter removing/deleting the APP and fresh install.

Thanks

**Comment by ChengappaMoEngage** [comment]
Thanks for the info. We are debugging this issue, will update you on this once fixed.

**Comment by apoorva-moengage** [comment]
Hi,

We are unable to reproduce this issue. I can arrange a quick call with my team. Please let me know when can we connect.

**Comment by ChengappaMoEngage** [comment]
@EasyTaxi-iOS: Thanks to your team for having a call with us on Friday. It really helped us to figure out the issue. We have fixed this crash in SDK version 3.8.1. Please update to the latest version for the fix.
