### ISSUE TITLE
"Unknown type name 'UNNotificationCategory'" when installed manually

### ISSUE THREAD

**Issue by zcsipler** [moengage/MoEngage-iOS-SDK#9]
Dear MoEngage team,

I install MoEngage manually and trying to use it in Swift. I did all the steps written in the manual, still when I build the project I got "Unknown type name

 **'UNNotificationCategory'; did you mean 'MONotificationCategory'?"** 

in MoEngage.h file. 

I also tried to add UserNotifications.framework to  linked frameworks but it didn't help.

You can reproduce the issue in my testProject available in github url:

https://github.com/zcsipler/testMoEngage.git

Thanks for the help in advance!

**Comment by ChengappaMoEngage** [comment]
Hi @zcsipler, not sure why this was happening in your project we haven't observed this issue with other users. I have update the UserNotification import statement in `MoEngage.h` file of SDK from version 4.0.0 so that you don't get this error. Updating to this version should take care of it.
